# ~/media-stack/docker-compose.yml
# This is the main file to run the entire stack.
# Command: docker compose up -d

name: media-stack

# --- Global Network Definition ---
networks:
  media-stack:
    driver: bridge

# --- Include all the component files ---
# The common file with anchors is included first.
include:
  - docker-compose.common.yml
  - docker-compose.core.yml
  - docker-compose.photos.yml
  # - docker-compose.downloaders.yml
  # - docker-compose.arr.yml
  - docker-compose.media-servers.yml
  - docker-compose.management.yml
  # - docker-compose.monitoring.yml
  # - docker-compose.files.yml
