#!/bin/bash
# generate-secrets.sh - Generate secure secrets for Docker media stack

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}Docker Media Stack Secret Generator${NC}"
echo "===================================="
echo ""

# Check if .env exists
if [ -f ".env" ]; then
    echo -e "${YELLOW}Warning: .env file already exists!${NC}"
    read -p "Do you want to backup existing .env? (y/n): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        backup_name=".env.backup.$(date +%Y%m%d_%H%M%S)"
        cp .env "$backup_name"
        echo -e "${GREEN}Backed up to: $backup_name${NC}"
    fi
    echo ""
fi

# Copy template if .env doesn't exist
if [ ! -f ".env" ]; then
    if [ -f ".env.example" ]; then
        cp .env.example .env
        echo -e "${GREEN}Created .env from .env.example${NC}"
    else
        echo -e "${RED}Error: .env.example not found!${NC}"
        exit 1
    fi
fi

# Function to generate secure random string
generate_secret() {
    openssl rand -hex 32
}

# Function to update or add secret in .env
update_secret() {
    local key=$1
    local value=$2
    
    if grep -q "^${key}=" .env; then
        # Update existing key
        sed -i.bak "s|^${key}=.*|${key}=${value}|" .env
    else
        # Add new key
        echo "${key}=${value}" >> .env
    fi
}

echo "Generating secure secrets..."
echo ""

# Generate Authelia secrets
echo "Generating Authelia secrets..."
update_secret "AUTHELIA_SESSION_SECRET" "$(generate_secret)"
update_secret "AUTHELIA_JWT_SECRET" "$(generate_secret)"
update_secret "AUTHELIA_STORAGE_ENCRYPTION_KEY" "$(generate_secret)"
update_secret "AUTHELIA_OIDC_HMAC_SECRET" "$(generate_secret)"

echo -e "${GREEN}✓ Authelia secrets generated${NC}"

# Generate password hash for Authelia user
echo ""
echo "Setting up Authelia user..."
read -p "Enter username for Authelia admin [admin]: " username
username=${username:-admin}

read -p "Enter email for Authelia admin: " email
while [[ ! "$email" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; do
    echo -e "${RED}Invalid email format!${NC}"
    read -p "Enter email for Authelia admin: " email
done

# Generate secure password
echo ""
echo "Generating secure password for Authelia..."
read -p "Do you want to enter your own password? (y/n): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    while true; do
        read -s -p "Enter password (min 12 chars): " password
        echo
        read -s -p "Confirm password: " password2
        echo
        
        if [ "$password" != "$password2" ]; then
            echo -e "${RED}Passwords don't match!${NC}"
        elif [ ${#password} -lt 12 ]; then
            echo -e "${RED}Password must be at least 12 characters!${NC}"
        else
            break
        fi
    done
else
    # Generate random secure password
    password=$(openssl rand -base64 16)
    echo -e "${YELLOW}Generated password: $password${NC}"
    echo -e "${YELLOW}SAVE THIS PASSWORD! You'll need it to login.${NC}"
fi

# Generate password hash
echo ""
echo "Generating password hash..."
if command -v docker &> /dev/null; then
    hash=$(docker run --rm authelia/authelia:latest authelia crypto hash generate argon2 --password "$password" 2>/dev/null | grep "Digest: " | cut -d' ' -f2)
    
    # Create users_database.yml
    cat > media-stack/authelia/users_database.yml << EOF
# Authelia users database
# Generated by generate-secrets.sh

users:
  ${username}:
    displayname: "${username^}"
    password: "${hash}"
    email: ${email}
    groups:
      - admins
      - users
EOF
    
    echo -e "${GREEN}✓ User database created${NC}"
else
    echo -e "${RED}Docker not found! Please install Docker and manually generate password hash.${NC}"
fi

# Check for required variables
echo ""
echo "Checking required variables..."

required_vars=(
    "DOMAIN_NAME"
    "VPN_SERVICE_PROVIDER"
    "OPENVPN_USER"
    "OPENVPN_PASSWORD"
    "TUNNEL_TOKEN"
    "PUID"
    "PGID"
    "TZ"
    "DOCKER_BASE_DIR"
    "DOCKER_MEDIA_DIR"
)

missing_vars=()
for var in "${required_vars[@]}"; do
    if ! grep -q "^${var}=..*" .env || grep -q "^${var}=.*_here\|^${var}=$" .env; then
        missing_vars+=("$var")
    fi
done

if [ ${#missing_vars[@]} -gt 0 ]; then
    echo -e "${YELLOW}The following variables need to be configured:${NC}"
    for var in "${missing_vars[@]}"; do
        echo "  - $var"
    done
    echo ""
    echo -e "${YELLOW}Please edit .env and add your values for these variables.${NC}"
else
    echo -e "${GREEN}✓ All required variables are set${NC}"
fi

# Set permissions
chmod 600 .env
chmod 600 media-stack/authelia/users_database.yml 2>/dev/null || true

echo ""
echo -e "${GREEN}Secret generation complete!${NC}"
echo ""
echo "Next steps:"
echo "1. Edit .env and fill in any missing values"
echo "2. Configure your DNS records"
echo "3. Run: docker-compose -f docker-compose-secure.yml up -d"
echo "4. Access https://auth.${DOMAIN_NAME} to set up 2FA"
echo ""
echo -e "${YELLOW}Remember to keep your .env file secure and never commit it to version control!${NC}"